/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab1;

public class StringCalculator {
    public int add(String numbers) {
        if (numbers == null || numbers.isEmpty()) {
            return 0;
        }
        
        // Розділяємо рядок на числа за допомогою коми
        String[] numberArray = numbers.split(",");
        
        int sum = 0;
        
        for (String num : numberArray) {
            try {
                int value = Integer.parseInt(num.trim());
                sum += value;
            } catch (NumberFormatException e) {
                // Ігноруємо некоректні числа
            }
        }
        
        return sum;
    }

    public static void main(String[] args) {
        StringCalculator calculator = new StringCalculator();
        
        System.out.println(calculator.add("1"));     // Виведе 1
        System.out.println(calculator.add("1,2"));   // Виведе 3
        System.out.println(calculator.add("1,2,3"));
    }
}
